# Site settings
title: slackoverflow
email: megancoffey0427@gmail.com
description: "Insights, inspiration, expertise and humor shared inside Springbox, a digital startegy company located in Austin, Texas."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: CoffeyMegan
github_username:  MeganCoffey

# Build settings
markdown: kramdown
permalink: pretty
